sudo: true
os:
  - linux
  - windows
    
language: generic

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

env: 
  - DIR="hw1-CLI"

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

install:
  - cd "$DIR"
  - stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - stack test --system-ghc

notifications:
  email: false
